language: node_js

addons:
  ssh_known_hosts:
  - emmental.fuelrats.com

cache: yarn

script:
- yarn run build

before_deploy:
- openssl aes-256-cbc -K $encrypted_257dda796125_key -iv $encrypted_257dda796125_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa

notifications:
  webhooks:
    urls:
      - http://orthanc.localecho.net/cgi-bin/webhook.py
      - https://announcer-dev.fuelrats.com/travis
    on_success: always
    on_failure: always

deploy:
- provider: script
  skip_cleanup: true
  script: bash scripts/deploy.sh
  on:
    all_branches: true
   
 
